sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project deejaygeroso
  - gcloud config set compute/zone asia-east1-a
  - gcloud container clusters get-credentials deejaygeroso-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash ./config/bash/setup_env.sh
  # - docker build -t deejaygeroso/deejaygeroso . --file ./config/docker/Dockerfile.prod
script:
  # - bash ./config/bash/setup_env.sh
  - docker run -e CI=true deejaygeroso/deejaygeroso npm run lint
deploy:
  provider: script
  script: bash ./config/bash/setup_env.sh && bash ./config/bash/deploy.sh
  on:
    branch: master
