version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.${ENV}
    container_name: app
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: on-failure
    volumes:
      - /app/node_modules
      - .:/app
