apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 34.80.219.32
    networking.gke.io/managed-certificates: app-certificate
spec:
  rules:
    - host:
        - deejaygeroso.com
          www.deejaygeroso.com
      http:
        paths:
          - path: /
            backend:
              serviceName: app-cluster-ip-service
              servicePort: 3000
